// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'commentContainer': string;
  'container': string;
  'editor': string;
  'heading': string;
  'loadingText': string;
  'modalContainer': string;
  'statusContainer': string;
  'submit': string;
  'successText': string;
  'widgetButtons': string;
  'widgetContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
