// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'editor': string;
  'heading': string;
  'infographic': string;
  'infographicContainer': string;
  'secondaryHeading': string;
  'submit': string;
  'title': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
