// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'editor': string;
  'editorContainer': string;
  'editorContainerColumnLeft': string;
  'editorContainerColumnRight': string;
  'editorContainerInput': string;
  'heading': string;
  'info': string;
  'secondaryHeading': string;
  'submit': string;
}
export const cssExports: CssExports;
export default cssExports;
