// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footerColumn': string;
  'footerList': string;
}
export const cssExports: CssExports;
export default cssExports;
