// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CodeMirror-scroll': string;
  'MuiCardHeader-title': string;
  'container': string;
  'editor': string;
  'editorContainer': string;
  'heading': string;
  'info': string;
  'loadingText': string;
  'statusContainer': string;
  'successText': string;
  'tag': string;
  'tagContainer': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
