// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CodeMirror-scroll': string;
  'container': string;
  'editor': string;
  'editorContainer': string;
  'heading': string;
  'loadingText': string;
  'statusContainer': string;
  'successText': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
