// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-btn-primary': string;
  'container': string;
  'header': string;
  'text': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
