// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loaderContainer': string;
  'loaderText': string;
}
export const cssExports: CssExports;
export default cssExports;
